package HakEdisDomain;

public class Degiskenler {

	static String[] mudurlukler= {"15 TEMMUZ ﬁEH›TLER PTT M‹D‹RL‹–‹",
			"150.YIL ANADOLU YAKASI POSTA ›ﬁLEME M‹D‹RL‹–‹",
			"50.YIL PTT M‹D‹RL‹–‹",
			"ACIBADEM KARGO DA–ITIM M‹D‹RL‹–‹",
			"ACIBADEM PTT M‹D‹RL‹–‹",
			"AKSARAY PTT M‹D‹RL‹–‹",
			"AL›BEYK÷Y PTT M‹D‹RL‹–‹",
			"ANADOLU YAKASI KARGO ›ﬁLEME M‹D‹RL‹–‹",
			"ARNAVUTK÷Y POSTA DA–ITIM M‹D‹RL‹–‹",
			"ARNAVUTK÷Y PTT M‹D‹RL‹–‹",
			"ATAﬁEH›R POSTA DA–ITIM M‹D‹RL‹–‹",
			"ATAﬁEH›R PTT M‹D‹RL‹–‹",
			"AVCILAR POSTA DA–ITIM M‹D‹RL‹–‹",
			"AVCILAR PTT M‹D‹RL‹–‹",
			"AVRUPA YAKASI KARGO ›ﬁLEME M‹D‹RL‹–‹",
			"AVRUPA YAKASI POSTA ›ﬁLEME M‹D‹RL‹–‹",
			"AYDINLI PTT M‹D‹RL‹–‹",
			"BA–CILAR POSTA DA–ITIM M‹D‹RL‹–‹",
			"BA–CILAR PTT M‹D‹RL‹–‹",
			"BAH«EL›EVLER KARGO DA–ITIM M‹D‹RL‹–‹",
			"BAH«EL›EVLER POSTA DA–ITIM M‹D‹RL‹–‹",
			"BAH«EL›EVLER PTT M‹D‹RL‹–‹",
			"BAH«EﬁEH›R PTT M‹D‹RL‹–‹",
			"BAKIRK÷Y ADL›YE PTT M‹D‹RL‹–‹",
			"BAKIRK÷Y POSTA DA–ITIM M‹D‹RL‹–‹",
			"BAKIRK÷Y PTT M‹D‹RL‹–‹",
			"BAﬁAKﬁEH›R KARGO DA–ITIM M‹D‹RL‹–‹",
			"BAﬁAKﬁEH›R POSTA DA–ITIM M‹D‹RL‹–‹",
			"BAﬁAKﬁEH›R PTT M‹D‹RL‹–‹",
			"BAﬁM‹D‹RL‹K",
			"BAYRAMPAﬁA POSTA DA–ITIM M‹D‹RL‹–‹",
			"BAYRAMPAﬁA PTT M‹D‹RL‹–‹",
			"BEﬁ›KTAﬁ POSTA DA–ITIM M‹D‹RL‹–‹",
			"BEﬁ›KTAﬁ PTT M‹D‹RL‹–‹",
			"BEYAZIT PTT M‹D‹RL‹–‹",
			"BEYKENT PTT M‹D‹RL‹–‹",
			"BEYKOZ POSTA DA–ITIM M‹D‹RL‹–‹",
			"BEYKOZ PTT M‹D‹RL‹–‹",
			"BEYL›KD‹Z‹ POSTA DA–ITIM M‹D‹RL‹–‹",
			"BEYL›KD‹Z‹ PTT M‹D‹RL‹–‹",
			"BEYO–LU POSTA DA–ITIM M‹D‹RL‹–‹",
			"BEYO–LU PTT M‹D‹RL‹–‹",
			"BO–AZ KARGO DA–ITIM M‹D‹RL‹–‹",
			"BOSTANCI PTT M‹D‹RL‹–‹",
			"B‹Y‹KADA PTT M‹D‹RL‹–‹",
			"B‹Y‹K«EKMECE PTT M‹D‹RL‹–‹",
			"«A–LAYAN KARGO DA–ITIM M‹D‹RL‹–‹",
			"«ATALCA PTT M‹D‹RL‹–‹",
			"«EKMEK÷Y POSTA DA–ITIM M‹D‹RL‹–‹",
			"«EKMEK÷Y PTT M‹D‹RL‹–‹",
			"DE–ERL› KA–ITLAR M‹D‹RL‹–‹",
			"DESTEK H›ZMETLER› VE ULAﬁIM M‹D‹RL‹–‹",
			"DUDULLU PTT M‹D‹RL‹–‹",
			"E–›T›M M‹D‹RL‹–‹",
			"ESENLER PTT M‹D‹RL‹–‹",
			"ESENYURT POSTA DA–ITIM M‹D‹RL‹–‹",
			"ESENYURT PTT M‹D‹RL‹–‹",
			"E-T›CARET M‹D‹RL‹–‹",
			"EYS M‹D‹RL‹–‹",
			"EY‹P POSTA DA–ITIM M‹D‹RL‹–‹",
			"EY‹P SULTAN PTT M‹D‹RL‹–‹",
			"FAT›H POSTA DA–ITIM M‹D‹RL‹–‹",
			"FAT›H PTT M‹D‹RL‹–‹",
			"FERHATPAﬁA PTT M‹D‹RL‹–‹",
			"FER›K÷Y PTT M‹D‹RL‹–‹",
			"FINDIKZADE PTT M‹D‹RL‹–‹",
			"GAYRETTEPE PTT M‹D‹RL‹–‹",
			"GAZ› MAHALLES› PTT M‹D‹RL‹–‹",
			"GAZ›OSMANPAﬁA PTT M‹D‹RL‹–‹",
			"G÷ZTEPE PTT M‹D‹RL‹–‹",
			"G‹LTEPE ﬁEH›T MEHMET AL› KILI« PTT M‹D‹RL‹–‹",
			"G‹NEﬁL› PTT M‹D‹RL‹–‹",
			"HADIMK÷Y PTT M‹D‹RL‹–‹",
			"HALKALI PTT M‹D‹RL‹–‹",
			"HUKUK M‹D‹RL‹–‹",
			"›K›TELL› PTT M‹D‹RL‹–‹",
			"›NSAN KAYNAKLARI M‹D‹RL‹–‹",
			"›STANBUL ADALET SARAYI PTT M‹D‹RL‹–‹",
			"›STANBUL ANADOLU ADALET SARAYI PTT M‹D‹RL‹–‹",
			"›STANBUL B÷LGE ›ST›NAF MAHKEMELER› PTT M‹D‹RL‹–‹",
			"›ST›NYE PTT M‹D‹RL‹–‹",
			"›STO« PTT M‹D‹RL‹–‹",
			"KADIK÷Y POSTA DA–ITIM M‹D‹RL‹–‹",
			"KADIK÷Y PTT M‹D‹RL‹–‹",
			"KA–ITHANE POSTA DA–ITIM M‹D‹RL‹–‹",
			"KA–ITHANE PTT M‹D‹RL‹–‹",
			"KARAK÷Y PTT M‹D‹RL‹–‹",
			"KARTAL KARGO DA–ITIM M‹D‹RL‹–‹",
			"KARTAL POSTA DA–ITIM M‹D‹RL‹–‹",
			"KARTAL PTT M‹D‹RL‹–‹",
			"KASIMPAﬁA PTT M‹D‹RL‹–‹",
			"KAVACIK PTT M‹D‹RL‹–‹",
			"KAYAﬁEH›R PTT M‹D‹RL‹–‹",
			"KAYNARCA PTT M‹D‹RL‹–‹",
			"KEMERBURGAZ PTT M‹D‹RL‹–‹",
			"KIRA« KARGO DA–ITIM M‹D‹RL‹–‹",
			"KIRA« PTT M‹D‹RL‹–‹",
			"KONTROL÷RL‹K",
			"KOORD›NASYON OF›S›",
			"KURTK÷Y POSTA DA–ITIM M‹D‹RL‹–‹",
			"KURTK÷Y PTT M‹D‹RL‹–‹",
			"K‹«‹K«EKMECE POSTA DA–ITIM M‹D‹RL‹–‹",
			"K‹«‹K«EKMECE PTT M‹D‹RL‹–‹",
			"K‹«‹KYALI PTT M‹D‹RL‹–‹",
			"LEVENT PTT M‹D‹RL‹–‹",
			"LOJ›ST›K H›ZMETLER› M‹D‹RL‹–‹",
			"MALTEPE POSTA DA–ITIM M‹D‹RL‹–‹",
			"MALTEPE PTT M‹D‹RL‹–‹",
			"MALTEPE PTT M‹D‹RL‹–‹",
			"MEC›D›YEK÷Y PTT M‹D‹RL‹–‹",
			"MERTER KERESTEC›LER S›TES› PTT M‹D‹RL‹–‹",
			"MUHASEBE VE F›NANS M‹D‹RL‹–‹",
			"PAZARLAMA VE SATIﬁ M‹D‹RL‹–‹",
			"PEND›K POSTA DA–ITIM M‹D‹RL‹–‹",
			"PEND›K PTT M‹D‹RL‹–‹",
			"POSTA-KARGO H›ZMETLER› M‹D‹RL‹–‹",			
			"PTTBANK M‹D‹RL‹–‹",
			"SAHRAYICED›T PTT M‹D‹RL‹–‹",
			"SAMANDIRA PTT M‹D‹RL‹–‹",
			"SANCAKTEPE KARGO DA–ITIM M‹D‹RL‹–‹",
			"SANCAKTEPE POSTA DA–ITIM M‹D‹RL‹–‹",
			"SANCAKTEPE PTT M‹D‹RL‹–‹",
			"SARIYER POSTA DA–ITIM M‹D‹RL‹–‹",
			"SARIYER PTT M‹D‹RL‹–‹",
			"SATINALMA M‹D‹RL‹–‹",
			"SEFAK÷Y PTT M‹D‹RL‹–‹",
			"SEYRANTEPE PTT M‹D‹RL‹–‹",
			"S›L›VR› POSTA DA–ITIM M‹D‹RL‹–‹",
			"S›L›VR› PTT M‹D‹RL‹–‹",
			"S›RKEC› PTT M‹D‹RL‹–‹",
			"SO–ANLIK PTT M‹D‹RL‹–‹",
			"SULTANBEYL› POSTA DA–ITIM M‹D‹RL‹–‹",
			"SULTANBEYL› PTT M‹D‹RL‹–‹",
			"SULTANGAZ› POSTA DA–ITIM M‹D‹RL‹–‹",
			"SULTANGAZ› PTT M‹D‹RL‹–‹",
			"ﬁ›LE PTT M‹D‹RL‹–‹",
			"ﬁ›R›NEVLER PTT M‹D‹RL‹–‹",
			"ﬁ›ﬁL› POSTA DA–ITIM M‹D‹RL‹–‹",
			"ﬁ›ﬁL› PTT M‹D‹RL‹–‹",
			"TAKS›M PTT M‹D‹RL‹–‹",
			"TEKNOLOJ› M‹D‹RL‹–‹",
			"TEﬁV›K›YE PTT M‹D‹RL‹–‹",
			"TOPKAPI KARGO DA–ITIM M‹D‹RL‹–‹",
			"TUZLA POSTA DA–ITIM M‹D‹RL‹–‹",
			"TUZLA PTT M‹D‹RL‹–‹",
			"ULUSLARARASI POSTA KARGO ›ﬁLEME M‹D‹RL‹–‹",
			"‹MRAN›YE POSTA DA–ITIM M‹D‹RL‹–‹",
			"‹MRAN›YE PTT M‹D‹RL‹–‹",
			"‹SK‹DAR POSTA DA–ITIM M‹D‹RL‹–‹",
			"‹SK‹DAR PTT M‹D‹RL‹–‹",
			"YAPI ›ﬁLER› M‹D‹RL‹–‹",
			"YEN› BOSNA PTT M‹D‹RL‹–‹",
			"YEﬁ›LK÷Y PTT M‹D‹RL‹–‹",
			"YILDIRIM PTT M‹D‹RL‹–‹",
			"ZEYT›NBURNU PTT M‹D‹RL‹–‹", 
			"Z‹MR‹TEVLER PTT M‹D‹RL‹–‹"};

	
	static String[] calismaGunleri= {"X","HT","RT","II","R2A","R2U","YI","OI","BI","EI","G","DI","C","SM","GM","YG","UI"};
	
	
	

	public static String[] getCalismaGunleri() {
		return calismaGunleri;
	}

	public static void setCalismaGunleri(String[] calismaGunleri) {
		Degiskenler.calismaGunleri = calismaGunleri;
	}

	public static String[] getMudurlukler() {
		return mudurlukler;
	}

	public void setMudurlukler(String[] mudurlukler) {
		this.mudurlukler = mudurlukler;
	}






}
